// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6d5yzvm_-WtD4djm0sxdpw6NVzulnXn4',
    appId: '1:177130790090:web:9224201c9b954baf57e833',
    messagingSenderId: '177130790090',
    projectId: 'gixatco',
    authDomain: 'gixatco.firebaseapp.com',
    storageBucket: 'gixatco.firebasestorage.app',
    measurementId: 'G-YZW1CLFRBX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_V2jxlNUtttCys4OmS7wrtegBaMbXRDM',
    appId: '1:177130790090:android:570d83b04723d24e57e833',
    messagingSenderId: '177130790090',
    projectId: 'gixatco',
    storageBucket: 'gixatco.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDt1D2Jq6aTVA4GZP2US-mykdQVLi16iQg',
    appId: '1:177130790090:ios:b5b0ff749981867157e833',
    messagingSenderId: '177130790090',
    projectId: 'gixatco',
    storageBucket: 'gixatco.firebasestorage.app',
    iosClientId:
        '177130790090-pcqomogolk84a7nq6r6rr2ji15o9gtaf.apps.googleusercontent.com',
    iosBundleId: 'com.gixat.gixatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDt1D2Jq6aTVA4GZP2US-mykdQVLi16iQg',
    appId: '1:177130790090:ios:b5b0ff749981867157e833',
    messagingSenderId: '177130790090',
    projectId: 'gixatco',
    storageBucket: 'gixatco.firebasestorage.app',
    iosClientId:
        '177130790090-pcqomogolk84a7nq6r6rr2ji15o9gtaf.apps.googleusercontent.com',
    iosBundleId: 'com.gixat.gixatapp',
  );
}
